seturl = "https://muryp.my.id/"
title = "MuryP Beta"
# theme = "muryp-now"
disqusShortname = "muryp"

[outputs]
    home = ["HTML", "RSS", "JSON"]
    pages = ["HTML", "RSS", "JSON"]
    page = ["HTML", "RSS", "JSON"]
    section = ["HTML", "RSS", "JSON"]

[taxonomies]
  tags = "tags"
  tags2 = "tags2"
  # author = "authors"

[permalinks]
  blog = "/blog/:slug/"
  note = "/note/:slug/"
  laman = "/pages/:slug/"
  # en = "/en/:slug/"

languageCode = "id-id"
DefaultContentLanguage = "id"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
languageCode = 'id-id'
[author]
  name = 'Alief Prihantoro'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

