[[main]]
identifier = "Home"
name = "Home"
url = "/"
weight = 1
[[main]]
identifier = "About"
name = "About"
url = "/about/"
weight = 2
[[main]]
identifier = "Kontak"
name = "Kontak"
url = "/contact/"
weight = 3
[[main]]
identifier = "Catatan"
name = "Catatan"
url = "/note/"
weight = 4
[[main]]
identifier = "Bookmark"
name = "Bookmark"
url = "/bookmark"
weight = 5
[[main]]
identifier = "Kumpulan Ide"
name = "Kumpulan Ide"
url = "/ideku/"
weight = 6
